### ISSUE TITLE
enable repo to use Kebechet and AICoE-CI

### ISSUE THREAD

**Issue by goern** [aicoe-aiops/pet-image-detection#3]
Hey there, please enable Kebechet and AICoE-CI for this repo. We are very interested in the integration of Seldon Core serving and the Thoth tooling. How can we recommend package updates? Do we build container image or will Seldon do so? ...

@sub-mod
@harshad16 
@pacospace

**Comment by isabelizimm** [comment]
Hello-- I have added a [.thoth.yaml](https://github.com/aicoe-aiops/pet-image-detection/blob/main/.thoth.yaml) file and both Kebechet and AICoE-CI are installed as apps in this repo. Let me know if more steps need to be done to enable these tools.

For Seldon Core, you have to build the container image (https://docs.seldon.io/projects/seldon-core/en/v0.2.7/reference/apis/crd.html) and can interact with your deployed model via the `seldon-core` python package. From using `seldon-core`, it seems to have dependency conflicts with many other commonly used packages (ie, using Seldon's `alibi` or tensorflow) so that may be a good place for Thoth to start.
